version: "3.8"

services:
  traefik:
    image: traefik:v2.11
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.pg.address=:5432"
      - "--api.dashboard=true"

      # ACME (Let's Encrypt via Cloudflare DNS-01)
      - "--certificatesresolvers.cf.acme.email=ctgschollar@gmail.com"
      - "--certificatesresolvers.cf.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.cf.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cf.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"

      # Trust my external traefik proxy
      - "--entrypoints.web.proxyprotocol.trustedips=192.168.3.91/32"
      - "--entrypoints.websecure.proxyprotocol.trustedips=192.168.3.91/32"


      # Prometheus metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addEntryPointsLabels=true"
      - "--metrics.prometheus.addRoutersLabels=true"
      - "--metrics.prometheus.addServicesLabels=true"
      - "--entrypoints.metrics.address=:9100"
      - "--metrics.prometheus.entryPoint=metrics"

    environment:
      ACME_EMAIL: "ctgschollar@gmail.com"
      DOMAIN_BASE: ".schollar.dev"

    env_file: /mnt/cephfs-configs/traefik/.env

    ports:
      - "80:80"
      - "443:443"
      - "5432:5432" # Postgres access
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/cephfs-configs/traefik/letsencrypt:/letsencrypt"

    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
      placement:
        constraints:
          - node.labels.traefik == true
        max_replicas_per_node: 1
        preferences:
          - spread: node.id
      update_config:
        parallelism: 1
        order: start-first     # start new task, then stop old (minimize downtime)
        failure_action: rollback
      labels:
        - "traefik.enable=true"
        # Optional: secure dashboard at https://traefik.schollar.dev
        - "traefik.http.routers.traefik.rule=Host(`traefik.schollar.dev`)"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls=true"
        - "traefik.http.routers.traefik.tls.certresolver=cf"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

        # Prometheus Blackbox monitoring
        - "prometheus.blackbox=true"
        - "metrics.probe_url=https://traefik.schollar.dev"

networks:
  default:
    external: true
    name: traefik-net

