version: "3.8"

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      PUID: "1000"
      PGID: "1000"
      UMASK: "002"
      # TZ: Africa/Johannesburg
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - calibre_web_config:/config
      - type: bind
        source: /mnt/shared/jellyfin/media/books         # ‚Üê your books library (ebooks + audiobooks)
        target: /books
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 0
      placement:
        constraints:
          - node.labels.media == true
      labels:
        traefik.enable: "true"
        traefik.docker.network: traefik-net

        # HTTPS router
        traefik.http.routers.calibre-web.rule: Host(`books.schollar.dev`)
        traefik.http.routers.calibre-web.entrypoints: websecure
        traefik.http.routers.calibre-web.tls: "true"
        traefik.http.routers.calibre-web.tls.certresolver: cf

        # Upstream service port
        traefik.http.services.calibre-web.loadbalancer.server.port: "8083"

        # Prometheus Blackbox monitoring
        prometheus.blackbox: "true"
        metrics.probe_url: "https://books.schollar.dev"

volumes:
  calibre_web_config:
    driver: linbit/linstor-docker-volume
    driver_opts:
      size: 1GB
      fs: "xfs"
      replicas: "2"
      storagepool: "pool_ssd"


networks:
  traefik-net:
    external: true
