- Media:
    - Jellyfin:
        href: https://jellyfin.schollar.dev
        icon: si-jellyfin
    - Sonarr (Series Download):
        href: https://sonarr.schollar.dev
        icon: si-sonarr
    - Radarr (Moveis Download):
        href: https://radarr.schollar.dev
        icon: si-radarr
    - QBittorrent (Torrents):
        href: http://qbittorent.schollar.dev
        icon: si-qbittornet

- HomeLab:
    - Traefik:
        href: https://traefik.schollar.dev
        icon: si:traefikproxy
    - Portainer:
        href: https://portainer.schollar.dev
        icon: si:portainer
    - Proxmox:
        - prx01:
            href: https://prx01.schollar.dev
            icon: si-proxmox
        - prx02:
            href: https://prx02.schollar.dev
            icon: si-proxmox
        - prx03:
            href: https://prx03.schollar.dev
            icon: si-proxmox
        - prx04:
            href: https://prx04.schollar.dev
            icon: si-proxmox
        - prx05:
            href: http://prx05.schollar.dev
            icon: si-proxmox
