---
# Inventory file for linstor backup deployment
# Docker Swarm nodes: dks01-dks05.schollar.dev

all:
  children:
    docker_swarm_nodes:
      hosts:
        dks01:
          ansible_host: dks01.schollar.dev
        dks02:
          ansible_host: dks02.schollar.dev
        dks03:
          ansible_host: dks03.schollar.dev
        dks04:
          ansible_host: dks04.schollar.dev
        dks05:
          ansible_host: dks05.schollar.dev
      vars:
        ansible_user: root
        ansible_python_interpreter: /usr/bin/python3
        ansible_ssh_private_key_file: "{{ inventory_dir }}/ansible_ssh_key"